apiVersion: v1
kind: Pod
metadata:
        name: nginxapp
spec:
    containers:
        - name: nginxcont
          image: nginx:latest
   resources:
              requests:
                  cpu: "50"
                  memory: "120"
    ports:
         protocol: TCP
         containerPort: 80
         name: http
                         